#You are given two strings s and t.
#String t is generated by random shuffling string s and then add one more letter at a random position.
#Return the letter that was added to t.

 

class Solution:
    def findTheDifference(self, s: str, t: str) -> str:
        t1=[i for i in t]
        for i in s:
            t1.remove(i)
        return "".join(t1)